# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
#linter:
#  rules:
#    - unnecessary_new

analyzer:
  errors:
    cascade_invocations: error
    unnecessary_const: error
    unnecessary_new: error
#   exclude:
#     - path/to/excluded/files/**
